### ISSUE TITLE
XSLT isn't adding class="cypher"/"decypher" to the HTML

### ISSUE THREAD

**Issue by azimmern** [azimmern/therologia#1]
I'm now noticing a lot of things that should have <span class="cypher"> or <span class="decypher> around them that instead just have <span>. So there's some problem going on with the XML<-> XLST connection. Need to ask Dan.

**Comment by randal-sean-harrison** [comment]
cool beans. 
Cheers,
Randy

Randal Sean Harrison, Ph.D.
Associate Librarian, Emerging Technologies
Hesburgh Libraries

Concurrent Teaching Professor, Management & Organization
Mendoza College of Business

University of Notre Dame
158 Hesburgh Library
Notre Dame, IN 46556

(574) 631-0312
***@***.*** ***@***.***>
randalseanharrison.com <https://randalseanharrison.com/>

⌖  Map to my office <https://randalseanharrison.com/img/map-to-my-office.svg>
⌖  Meet with me <https://calendly.com/randal-sean-harrison/consultation>
